version: "3.3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/src
      
  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - .:/src
        
  celery_worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A monolith.app.celery worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - .:/src

  celery_beat:
    build:
      context: .
    command: celery -A monolith.app.celery beat --loglevel=info
    volumes:
      - .:/src
    depends_on:
      - redis

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888